/*
 * AAandAGFilterDialog.java
 *
 * Created on April 29, 2003, 5:17 PM
 */

package rheat.GUI;

import rheat.base.*;
import rheat.filter.AAandAGHelicesFilter;
import rheat.filter.Filter;

/**
 *
 * @author  jyzhang
 */
public class AAandAGFilterDialog
extends FilterDialog {

    public AAandAGFilterDialog() {
        super("AA and AG Filter");
        initComponents();
    }

    /**
     * Implements FilterDialog interface.
     */
    public rheat.filter.Filter getNewFilter() {
        return filter;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("AA and AG Helix end filter.");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
    }//GEN-END:initComponents

    /**
     * Implementation of interface method; commits changes (as the
     * user has accepted the dialog).
     */
    void actionPanelAccepted() {
        this.filter = new AAandAGHelicesFilter();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private Filter filter; // null unless dialog was accepted by user

}
