/*
 * BasicFilterDialog.java
 *
 * Created on April 3, 2003, 5:17 PM
 */

package rheat.GUI;

import rheat.base.*;
import rheat.filter.AllHelicesFilter;
import rheat.filter.BPFilter;

/**
 *
 * @author  jyzhang
 */
public class BasepairFilterDialog extends javax.swing.JDialog {
    
    private int mode;
    private RNA _rna;
    
    /** Creates new form BasicFilterDialog */
    public BasepairFilterDialog(RNA rna, int m, java.awt.Frame parent) {
        super(parent, true);
        _rna = rna;
        mode = m;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cgCheckBox = new javax.swing.JCheckBox();
        auCheckBox = new javax.swing.JCheckBox();
        guCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        aaCheckBox = new javax.swing.JCheckBox();
        acCheckBox = new javax.swing.JCheckBox();
        agCheckBox = new javax.swing.JCheckBox();
        ccCheckBox = new javax.swing.JCheckBox();
        cuCheckBox = new javax.swing.JCheckBox();
        ggCheckBox = new javax.swing.JCheckBox();
        uuCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        acceptBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Basepair Filter");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Please choose the basepairings");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        cgCheckBox.setSelected(true);
        cgCheckBox.setText("C-G");
        jPanel2.add(cgCheckBox);

        auCheckBox.setSelected(true);
        auCheckBox.setText("A-U");
        jPanel2.add(auCheckBox);

        guCheckBox.setSelected(true);
        guCheckBox.setText("G-U");
        jPanel2.add(guCheckBox);

        getContentPane().add(jPanel2);

        aaCheckBox.setText("A-A");
        jPanel4.add(aaCheckBox);

        acCheckBox.setText("A-C");
        jPanel4.add(acCheckBox);

        agCheckBox.setText("A-G");
        jPanel4.add(agCheckBox);

        ccCheckBox.setText("C-C");
        jPanel4.add(ccCheckBox);

        cuCheckBox.setText("C-U");
        jPanel4.add(cuCheckBox);

        ggCheckBox.setText("G-G");
        jPanel4.add(ggCheckBox);

        uuCheckBox.setText("U-U");
        jPanel4.add(uuCheckBox);

        getContentPane().add(jPanel4);

        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        jPanel3.add(acceptBtn);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jPanel3.add(cancelBtn);

        getContentPane().add(jPanel3);

        pack();
    }//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        BPFilter bpfilter = new BPFilter();
        String d = "Basepairs selected: \n";
        this.setVisible(false);
        int[] filterOptions = new int[10];
        // get the selected basepair types.
        if (this.ccCheckBox.isSelected()){
            filterOptions[0] = BasepairType.CC;
            d += "C-C \n";
        }
        if (this.cgCheckBox.isSelected()){
            filterOptions[1] = BasepairType.CG;
            d += "C-G \n";
        }
        if (this.cuCheckBox.isSelected()){
            filterOptions[2] = BasepairType.CU;
            d += "C-U \n";
        }
        if (this.aaCheckBox.isSelected()){
            filterOptions[3] = BasepairType.AA;
            d += "A-A\n";
        }
        if (this.acCheckBox.isSelected()){
            filterOptions[4] = BasepairType.AC;
            d += "A-C\n";
        }
        if (this.agCheckBox.isSelected()){
            filterOptions[5] = BasepairType.AG;
            d += "A-G\n";
        }
        if (this.auCheckBox.isSelected()){
            filterOptions[6] = BasepairType.AU;
            d += "A-U\n";
        }
        if (this.ggCheckBox.isSelected()){
            filterOptions[7] = BasepairType.GG;
            d += "G-G\n";
        }
        if (this.guCheckBox.isSelected()){
            filterOptions[8] = BasepairType.GU;
            d += "G-U\n";
        }
        if (this.uuCheckBox.isSelected()){
            filterOptions[9] = BasepairType.UU;
            d += "U-U\n";
        }
        bpfilter.setArguments(filterOptions);
        if (mode == FilterController.INTERACTIVE){
            FilterController.rna = bpfilter.apply(_rna);
            FilterController.rna = (new AllHelicesFilter()).apply(FilterController.rna);
            FilterController.success = true;
            FilterController.description = d;
        }
        else if (mode == FilterController.BATCH){
            
        }
        System.out.println("Closing");
        this.close();
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        FilterController.success = false;
        close();
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    public void close(){
        dispose();
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        FilterController.success = false;
        close();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new BasepairFilterDialog(null, 0, new javax.swing.JFrame()).setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox auCheckBox;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JCheckBox ccCheckBox;
    private javax.swing.JCheckBox ggCheckBox;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox agCheckBox;
    private javax.swing.JCheckBox uuCheckBox;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox cuCheckBox;
    private javax.swing.JCheckBox aaCheckBox;
    private javax.swing.JCheckBox acCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox cgCheckBox;
    private javax.swing.JCheckBox guCheckBox;
    private javax.swing.JButton cancelBtn;
    // End of variables declaration//GEN-END:variables
    
}
