/*
 * DiagonalFilterDialog.java
 *
 * Created on April 29, 2003, 11:20 AM
 */

package rheat.GUI;

import rheat.base.*;
import rheat.filter.BasePairRangeHelicesFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author  jyzhang
 */
public class DiagonalFilterDialog extends javax.swing.JDialog {
    
    private RNA _rna;
    private int mode;
    
    /** Creates new form DiagonalFilterDialog */
    public DiagonalFilterDialog(RNA r, int m, java.awt.Frame parent) {
        super(parent, true);
        _rna = r;
        mode = m;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        minDistanceField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        maxDistanceField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("Diagonal Filter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Specify the helix range from the diagonal");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Minimum Distance");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel2.add(jLabel2);

        minDistanceField.setColumns(4);
        minDistanceField.setText("1");
        jPanel2.add(minDistanceField);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Maximum Distance");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel3.add(jLabel3);

        maxDistanceField.setColumns(4);
        maxDistanceField.setText("none");
        jPanel3.add(maxDistanceField);

        getContentPane().add(jPanel3);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton2);

        getContentPane().add(jPanel4);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BasePairRangeHelicesFilter filter = new BasePairRangeHelicesFilter();
        try {
            int min = 1; 
            int max = Integer.MAX_VALUE;
            min = Integer.parseInt(this.minDistanceField.getText());
            String maxS = this.maxDistanceField.getText();
            if (!(maxS.equals("NONE") || maxS.equals("none"))){
                max = Integer.parseInt(maxS);
            }
            if (min < 1){
                throw new RuntimeException ("Minimum must be >= 1");
            }
            if (min >= max){
                throw new RuntimeException ("Minimum cannot be >= maximum.");
            }
            this.setVisible(false);
            if (mode == FilterController.INTERACTIVE){
                String d = "Minimum distance from diagonal: " + min + "\n";
                d += "Maximum distance from diagonal: " + max + "\n";
                filter.setArguments(min, max);
                FilterController.rna = filter.apply(_rna);
                FilterController.success = true;
                FilterController.description = d;
            }
            else if (mode == FilterController.BATCH){
                
            }
            System.out.println("Closing");
            this.close();
        }
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid Input: Bad number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (RuntimeException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FilterController.success = false;
        close();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void close(){
        
        dispose();
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        FilterController.success = false;
        close();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DiagonalFilterDialog(null, 0, new javax.swing.JFrame()).setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField minDistanceField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxDistanceField;
    // End of variables declaration//GEN-END:variables
    
}
