/*
 * ELoopFilterDialog.java
 *
 * Created on April 29, 2003, 5:17 PM
 */

package rheat.GUI;

import rheat.base.*;
import rheat.filter.ELoopHelicesFilter;
import rheat.filter.Filter;

/**
 *
 * @author  jyzhang
 */
public class ELoopFilterDialog
extends javax.swing.JDialog
implements FilterDialog {

    /** Creates new form ELoopFilterDialog */
    public ELoopFilterDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * Implements FilterDialog interface.
     */
    public rheat.filter.Filter run() {
        pack();
        setLocationRelativeTo(getParent());
        setVisible(true); // blocks until dialog is done
        return filter;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("E-Loop Filter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("E-Loop Filter");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        getContentPane().add(jPanel2);

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        ELoopHelicesFilter newFilter = new ELoopHelicesFilter();
        this.setVisible(false);
        this.close();
        this.filter = newFilter;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        close();
    }

    private void close(){
        dispose();
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ELoopFilterDialog(new javax.swing.JFrame()).setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
    private Filter filter; // null unless dialog was accepted by user

}
