/*
 * ELoopFilterDialog.java
 *
 * Created on April 29, 2003, 5:17 PM
 */

package rheat.GUI;

import rheat.base.*;
import rheat.filter.ELoopHelicesFilter;
import rheat.filter.Filter;

/**
 *
 * @author  jyzhang
 */
public class ELoopFilterDialog
extends FilterDialog {

    public ELoopFilterDialog() {
        super("E-Loop");
        initComponents();
    }

    /**
     * Implements FilterDialog interface.
     */
    public rheat.filter.Filter getNewFilter() {
        return filter;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("(This currently has no parameters.)");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
    }

    /**
     * Implementation of interface method; commits changes (as the
     * user has accepted the dialog).
     */
    void actionPanelAccepted() {
        ELoopHelicesFilter newFilter = new ELoopHelicesFilter();
        this.filter = newFilter;
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
    private Filter filter; // null unless dialog was accepted by user

}
