/*
 * ELoopFilterDialog.java
 *
 * Created on April 29, 2003, 5:17 PM
 */

package rheat.GUI;

import rheat.test.*;
/**
 *
 * @author  jyzhang
 */
public class ELoopFilterDialog extends javax.swing.JDialog {
    
    private int mode;
    private RNA _rna;
    
    /** Creates new form ELoopFilterDialog */
    public ELoopFilterDialog(RNA r, int m, java.awt.Frame parent) {
        super(parent, true);
        _rna = r;
        mode = m;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("E-Loop Filter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("E-Loop Filter");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        getContentPane().add(jPanel2);

        pack();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        ELoopHelicesFilter filter = new ELoopHelicesFilter();
        this.setVisible(false);
        if (mode == FilterController.INTERACTIVE){
            FilterController.rna = filter.apply(_rna);
            FilterController.success = true;
        }
        else if (mode == FilterController.BATCH){
            
        }
        this.close();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        FilterController.success = false;
        close();
    }
    
    private void close(){
        
        dispose();
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        FilterController.success = false;
        close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ELoopFilterDialog(null, 0, new javax.swing.JFrame()).setVisible(true);
    }
    
    
    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
    
}

