/*
 * EnergyFilterDialog.java
 *
 * Created on May 5, 2003, 10:17 AM
 */

package rheat.GUI;

import rheat.base.*;
import rheat.filter.EnergyMaxMinFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author  jyzhang
 */
public class EnergyFilterDialog extends javax.swing.JDialog {
    
    private RNA _rna;
    private int mode;
    
    /** Creates new form DiagonalFilterDialog */
    public EnergyFilterDialog(RNA r, int m, java.awt.Frame parent) {
        super(parent, true);
        _rna = r;
        mode = m;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        minGField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        maxGField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("Energy Filter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Specify the helix energetic stability");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Maximum Stability (Low G value)");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 16));
        jPanel2.add(jLabel2);

        minGField.setColumns(4);
        minGField.setText("none");
        jPanel2.add(minGField);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Minimum Stability (High G value)");
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 16));
        jPanel3.add(jLabel3);

        maxGField.setColumns(4);
        maxGField.setText("none");
        jPanel3.add(maxGField);

        getContentPane().add(jPanel3);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton2);

        getContentPane().add(jPanel4);

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        EnergyMaxMinFilter filter = new EnergyMaxMinFilter();
        try {
            double min = Double.NEGATIVE_INFINITY; 
            double max = Double.POSITIVE_INFINITY;
            String maxG = this.maxGField.getText();
            String minG = this.minGField.getText();
            if (!(maxG.equals("NONE") || maxG.equals("none"))){
                max = Double.parseDouble(maxG);
            }
            if (!(minG.equals("NONE") || minG.equals("none"))){
                min = Double.parseDouble(minG);
            }
            if (min >= max){
                throw new RuntimeException ("Minimum G value must be less than Maximum G value");
            }
            this.setVisible(false);
            if (mode == FilterController.INTERACTIVE){
                String d = "Minimum G Value: " + min + "\n";
                d += "Maximum G Value: " + max + "\n";
                filter.setArguments(min, max);
                FilterController.rna = filter.apply(_rna);
                FilterController.success = true;
                FilterController.description = d;
            }
            else if (mode == FilterController.BATCH){
                
            }
            System.out.println("Closing");
            this.close();
        }
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid Input: Bad number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (RuntimeException ex){
            JOptionPane.showMessageDialog(this, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        FilterController.success = false;
        close();
    }
    
    private void close(){
        dispose();
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        FilterController.success = false;
        close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new EnergyFilterDialog(null, 0, new javax.swing.JFrame()).setVisible(true);
    }
    
    
    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField minGField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField maxGField;
    // End of variables declaration
    
}

